apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: reseat
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reseat
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: reseat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: user-service
          image: ghcr.io/prgrms-be-adv-devcourse/beadv7_7_overtimekk_be/user-service:v1.1.0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: user-config
          env:
            - name: TZ
              value: Asia/Seoul
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: MAIL_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 35
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: reseat
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
